### PR TITLE
pull request to fix issue #302

### PR DESCRIPTION
**Pull request by nashspence**
#302

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Wow, interesting issue. Surprised this hasn't come up before.

The test failure is because the test isn't formatted with prettier. You can run `npm run prettify`. I otherwise ran the tests locally and everything looks good. Thanks for the contribution!

**Comment by nashspence** [comment]
No worries. Yah, we were a bit surprised too but there you have it. I’ll check into the formatting issue, I thought I had prettier’ed it but I must have forgotten.

**Comment by nashspence** [comment]
In running the npm script for prettier I get a lot of changes unrelated to this issue. Would you like those included? Otherwise, I’m seeing no changes on the files this touches.

**Comment by mAAdhaTTah** [comment]
I wonder if it's a prettier version mismatch. It kinda looks similar on the Travis output (other files are failing but not the one you changed), but when I run it locally, I only get a change in your file. Two questions:

1. What's your node & npm version?
2. Did you install with `npm install` or `npm ci`?

**Comment by nashspence** [comment]
Could for sure be something like that. I’ll try reinstalling and testing it again. Node v13.13.0

**Comment by nashspence** [comment]
Yay, totally my bad on that one. I had included my fork in my mono-repo as a submodule when figuring out the issue, which does dependency hoisting and whatnot. After isolating it and using the normal npm install procedure I’m seeing what you’re seeing and all is well. Will update the PR in a second here

**Comment by nashspence** [comment]
Hm, still failing I see.

**Comment by mAAdhaTTah** [comment]
Only Node 6. My guess is the older npm version installs a newer version of prettier. I'm going to merge & fix this in a separate PR.

Thank you for the contribution!

**Comment by nashspence** [comment]
No worries. Thanks for what you do as well!

**Comment by mAAdhaTTah** [comment]
This has been published as v3.8.7

**Pull request merged**
