### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by bpinto**
I'm not sure what is your opinion on adding an "official" docker setup to kefir? This would make it easier for docker users - like myself - to open PRs.

### CODE REVIEW

**Comment by Macil** [comment]
Is this primarily intended to help people that don't have node installed on their system? (In other software ecosystems, I imagine one goal would be to prevent dependency conflicts in dependencies installed globally in the system, but for node since npm installs dependencies per-project that doesn't apply much here.) Just trying to understand the specific goal here.

Could you add a small bit to the readme at the end of the Development section describing how this could be used and what situation it would be good for? ("If you don't have Node.js installed on your system and you're using Docker, you can run this command to open a terminal inside this repository with a Node.js environment ready: `docker-something ...`")

**Comment by bpinto** [comment]
> Is this primarily intended to help people that don't have node installed on their system?

That's one of the main reasons, yes. That's what I do on my system. The second reason is for generating repeated code, on https://github.com/kefirjs/kefir/pull/317 you've asked me to use latest versions of `npm` which eventually could mean someone is not using the latest (e.g. npm launches a new version after my commit). To solve this potential inconsistency, one could define a dockerfile where all the main packages (node, npm) are pinned and then `package-lock.json` and `dist/*` files would always be the same - as long as everyone used the docker file - and we could add CI job where it would generate these files using docker so we could add an automated check that these files were correctly generated.

> Could you add a small bit to the readme at the end of the Development section describing how this could be used and what situation it would be good for? ("If you don't have Node.js installed on your system and you're using Docker, you can run this command to open a terminal inside this repository with a Node.js environment ready: docker-something ...")

I'll do my best! English is not my main language, but I am sure we will get it right! :)

**Comment by bpinto** [comment]
@Macil I've updated the dockerfile to install latest npm and also updated the documentation to mention docker.

**Comment by bpinto** [comment]
@Macil sorry to ping you again, but have you had the chance to look at the changes? Not having these files makes working on new features a little bit hard since I need to constantly cherry-pick/remove the commits before opening PRs.

**Pull request closed without merging**
