### PR TITLE
Add missing Flow annotation for Pool.unplug

### LINKED ISSUE #288: Missing type for `unplug`
The current Flow types don't include the type for `unplug`, just `plug`.

### PR DESCRIPTION
**Pull request by Macil**
Fixes #288.

----

@rpominov @mAAdhaTTah
I renamed my npm account semi-recently from agentme -> [macil](https://www.npmjs.com/settings/macil/packages) which for some kind of npm reasons caused me to lose publish permissions to any packages not originally created by me including kefir, so I'll need to be re-added to the npm package access list.  

Normally for any changes to Kefir, I'd put a PR up and wait for an approval review from another maintainer before merging, updating the changelog, and releasing, but for very trivial fixes like this, would you all prefer for me to merge my PR and release it immediately without waiting for a review, or prefer for me to always still wait for a review?

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Generally prefer reviews–not that I don't trust you :D–but I think it's a better practice. I should be able to give you publish rights though.

**Comment by mAAdhaTTah** [comment]
You should have publish rights now.

**Comment by mAAdhaTTah** [comment]
@Macil Give it a shot, let me know if you successfully publish. You may need to update the CHANGELOG, actually.

**Comment by Macil** [comment]
I don't seem to have publish access yet. (I get the error 'You do not have permission to publish "kefir". Are you logged in as the correct user? : kefir' from npm, and https://www.npmjs.com/package/kefir doesn't show me as a collaborator.)

**Comment by mAAdhaTTah** [comment]
screen shot 2019-01-06 at 8 53 26 pm

Do you have to accept it on your end? If you got to your list of packages in your profile, is it missing?

**Comment by Macil** [comment]
I tried it again and it worked now! Maybe the change took time to propagate through npm's side.

**Pull request merged**
